name: mmiv-dln-img

channels:
  - simpleitk
  - conda-forge
  - anaconda
  - pytorch

dependencies:
  - python==3.8
  - jupyter
  - ipython
  - ipykernel
  - jupyterlab
  - matplotlib
  - pip
  - git
  - gdown
  - ipywidgets
  - numpy
  - scipy
  - pandas
  - openpyxl
  - seaborn
  - SimpleITK
  - scikit-image
  - scikit-plot
  - dipy
  - imageio
  - tifffile
  - statsmodels
  - nibabel
  - nilearn
  - pycaret==2.3
  - networkx
  - pytorch
  - torchvision
